working_directory = "C:/Users/Chris/dev"

[font]
size = 14.0
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }

[window]
opacity = 0.98 

[window.padding]
x = 4
y = 4

